# Pipeline Configuration
# Central configuration for data fetching, notebook rendering, and deployment

version: "1.0"

# ============================================
# Date Range Configuration
# ============================================
dates:
  # Mode: "rolling" | "range" | "list"
  mode: rolling

  # For mode: rolling - relative to today
  # Generates dates from (today - window) to yesterday
  # Optional start: won't go earlier than this date
  rolling:
    window: 365 # Number of days to keep (yesterday through N days ago)
    start: "2025-12-03" # Optional: earliest date to include

  # For mode: range - fixed date boundaries
  # Required: start date
  # Optional: end date (defaults to yesterday if omitted)
  # range:
  #   start: "2025-12-01"
  #   end: "2025-12-31"  # Optional: defaults to yesterday

  # For mode: list - explicit dates
  # list:
  #   - "2025-12-15"
  #   - "2025-12-16"
  #   - "2025-12-17"

# ============================================
# Query Registry
# ============================================
queries:
  blobs_per_slot:
    module: queries.blob_inclusion
    function: fetch_blobs_per_slot
    description: Blobs per slot timeseries
    output_file: blobs_per_slot.parquet

  blocks_blob_epoch:
    module: queries.blob_inclusion
    function: fetch_blocks_blob_epoch
    description: Block counts by blob count per epoch
    output_file: blocks_blob_epoch.parquet

  blob_popularity:
    module: queries.blob_inclusion
    function: fetch_blob_popularity
    description: Blob count popularity per epoch
    output_file: blob_popularity.parquet

  slot_in_epoch:
    module: queries.blob_inclusion
    function: fetch_slot_in_epoch
    description: Blob count per slot within epoch
    output_file: slot_in_epoch.parquet

  blob_flow:
    module: queries.blob_flow
    function: fetch_blob_flow
    description: Proposer blobs with MEV relay data
    output_file: blob_flow.parquet

  col_first_seen:
    module: queries.column_propagation
    function: fetch_col_first_seen
    description: Column first seen timing across 128 subnets
    output_file: col_first_seen.parquet

  tx_per_slot:
    module: queries.mempool_visibility
    function: fetch_tx_per_slot
    description: Transaction counts per slot per type
    output_file: tx_per_slot.parquet

  mempool_coverage:
    module: queries.mempool_visibility
    function: fetch_mempool_coverage
    description: Hourly mempool coverage and wait time stats
    output_file: mempool_coverage.parquet

  sentry_coverage:
    module: queries.mempool_visibility
    function: fetch_sentry_coverage
    description: Per-sentry mempool coverage rates
    output_file: sentry_coverage.parquet

# ============================================
# Notebook Registry
# ============================================
notebooks:
  - id: blob-inclusion
    title: Blob Inclusion
    description: Analysis of blob inclusion patterns in Ethereum mainnet blocks
    icon: Layers
    source: notebooks/01-blob-inclusion.ipynb
    schedule: daily
    queries:
      - blobs_per_slot
      - blocks_blob_epoch
      - blob_popularity
      - slot_in_epoch
    parameters:
      - name: target_date
        type: date
        required: true
    order: 1

  - id: blob-flow
    title: Blob Flow
    description: Flow diagrams tracing blob packing per entities, builders, and relays
    icon: Activity
    source: notebooks/02-blob-flow.ipynb
    schedule: daily
    queries:
      - blob_flow
    parameters:
      - name: target_date
        type: date
        required: true
    order: 2

  - id: column-propagation
    title: Column Propagation
    description: Column propagation timing across 128 data columns subnets
    icon: Grid3x3
    source: notebooks/03-column-propagation.ipynb
    schedule: daily
    queries:
      - col_first_seen
    parameters:
      - name: target_date
        type: date
        required: true
    order: 3

  - id: mempool-visibility
    title: Mempool Visibility
    description: Transaction visibility in the public mempool before block inclusion
    icon: Eye
    source: notebooks/04-mempool-visibility.ipynb
    schedule: daily
    queries:
      - tx_per_slot
      - mempool_coverage
      - sentry_coverage
    parameters:
      - name: target_date
        type: date
        required: true
    order: 4

# Schedule options: hourly, daily, weekly, manual
# - hourly: Runs every hour, accumulating data throughout the day
# - daily: Runs once per day at 1am UTC
# - weekly: Runs once per week on Sundays at 2am UTC
# - manual: Only runs on manual dispatch

# ============================================
# Settings
# ============================================
settings:
  network: mainnet
  timezone: UTC
  data_dir: notebooks/data
  rendered_dir: site/rendered
  parallel_workers: 4
